workflows:
  ios-workflow:
    name: iOS Workflow

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lindseybarnard.cookbook

    scripts:
      - flutter pub get
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true