workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      flutter: stable

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lindseybarnard.cookbook

    scripts:
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa